### ISSUE TITLE
Consider migrating to the GitHub Actions or Travis CI Com

### ISSUE THREAD

**Issue by peter279k** [lotfio/skeleton#4]
As title, it should concern following message:

```
Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.
```

And it should migrate to GitHub Actions or Travis CI Com.

**Comment by lotfio** [comment]
Thanks for pointing out Peter, i am aware of it i will be moving all packages to **jenkins.lotfio.net**  soon :)

**Comment by peter279k** [comment]
Thanks. Closed.
